### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by montogeek** [eventualbuddha/babelrc-rollup#5]
Hi!

Great plugin, I have been using it, thanks :)

The rollup community has a convention (not official, I think) to rename its plugins with the following format `rollup-plugin-${name}`, this convention allow users to easily discover packages.

It would be great if this plugin adopted it

**Comment by eventualbuddha** [comment]
Thanks for the kind words! I'm aware of that convention, but chose not to follow it for a few reasons:
1. This is not a rollup plugin. In fact, there's nothing particularly rollup-specific about it. All it does is tweak your babel config to exclude modules.
2. There is already a rollup-plugin-babel, and naming this rollup-plugin-babelrc would likely cause confusion.

Perhaps a better name would actually be babelrc-without-modules?

**Comment by montogeek** [comment]
Yes, it not exactly a rollup plugin, I think is ok like this :)
Thanks for caring!
